Desktop/Dance-prj-main/platformdance/accounts/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    
]

Desktop/Dance-prj-main/platformdance/platformdance/urls.py
from django.contrib import admin
from django.urls import path, include
from danceapp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # 관리자 페이지는 배포시에 삭제
    path('admin/', admin.site.urls),
    # 계정 관련 url은 accounts/urls.py 에서 처리
    path('accounts/', include('accounts.urls')),
    
    # 메인 홈페이지
    path('', views.index, name='index'),
    # about us
    path('aboutus/', views.aboutus, name='aboutus'),

    # 마이페이지
    path('mypage/<int:user_id>', views.mypage, name='mypage'),
    # user 프로필 이미지 수정
    path('modifyprofileimg/<int:user_id>', views.modifyprofileimg, name='modifyprofileimg'),
    # 게시글 생성 (영상 업로드)
    path('postcreate/', views.postcreate, name='postcreate'),
    # 게시글 생성 (클래스 업로드)
    path('coursecreate/', views.coursecreate, name='coursecreate'),
    
    # 게시글 세부 페이지 보기
    path('post_detail/<int:post_id>', views.post_datail, name='post_detail'),
    # user 에 따른 개인 포스트 보기
    path('user_post_detail/<int:userId_id>', views.user_post_detail, name='user_post_detail'),
    # 게시글 삭제
    path('delete_post/<int:post_id>', views.delete_post, name='delete_post'),
    # 클래스 삭제
    
    # 댓글 달기
    path('new_comment/<int:post_id>', views.new_comment, name='new_comment'),
    # 댓글 삭제
    path('delete_comment/<int:comment_id>', views.delete_comment, name='delete_comment'),

    # 영상 / 클래스 좋아요
    path('likes/<int:post_id>', views.likes, name='likes'), # 게시글(영상)
    path('course_likes/<int:course_id>', views.course_likes, name='course_likes'), # 클래스
    
    # 게시글 수정
    path('modify_post/<int:post_id>', views.modify_post, name='modify_post'),

    # 클래스 전체 보기
    path('course', views.course, name='course'),

    # 장르별 영상 포스트 보기 / # 장르별 클래스 보기
    path('genre_post', views.genre_post, name='genre_post'),
    path('genre_course', views.genre_course, name='genre_course'),

    # 클래스 세부 페이지
    path('course_detail/<int:course_id>', views.course_detail, name='course_detail'),
    
    # 클래스 신청
    path('regCourse/<int:course_id>', views.regCourse, name='regCourse'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/Dance-prj-main/platformdance/danceapp/models.py
from cProfile import label
from django.db import models
# from django.contrib.auth.models import User
from accounts.models import userProfile

# Create your models here.
# 장르 모델
class Genre(models.Model):
    id = models.AutoField(primary_key=True, null=False) # pk 
    name = models.CharField(max_length=20) # 장르 이름

    def __str__(self):
        return self.name

# user가 작성한 게시글 모델        
class Post(models.Model):
    # 게시글ID, 회원ID, 장르ID, 제목, 내용, 작성시간, 수정시간, 썸네일, 비디오
    # 게시글ID는 primarykey로서 이미 있음
    userId = models.ForeignKey(userProfile, on_delete=models.CASCADE) # 회원ID # User 모델의 pk를 가져옴
    title = models.CharField(max_length=200) # 제목
    body = models.TextField() # 게시물 설명
    uploadDate = models.DateTimeField(auto_now_add=True) # 처음 업로드 시간
    updateDate = models.DateTimeField(auto_now=True) # 수정 시간
    photo = models.ImageField(blank=True, null=True, upload_to='thumbnail') # 썸네일 # upload_to : static/blog_photo 로 저장해줘
    video = models.FileField(blank=True, null=True, upload_to='video') # 배포시에는 models.FilePathField()사용
    genreName = models.ForeignKey(Genre, null=True, on_delete=models.CASCADE) # 장르
    likes_user = models.ManyToManyField(userProfile, related_name='likes', blank=True) # 좋아요 누른 사람
    likes_count = models.PositiveIntegerField(default=0) # 좋아요 개수
    hits = models.PositiveIntegerField(default=0) # 조회수

    def __str__(self):
        return self.title

# class LikePost(models.Model):
#     user = models.ForeignKey(userProfile, on_delete=models.CASCADE, related_name="liked_users")
#     post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="liked_posts")

#     def __str__(self):
#         return f"{self.user} liked {self.post}"


# 강좌 클래스 모델 만들기
class Course(models.Model):
    # pk=course_id 로 두기
    userId = models.ForeignKey(userProfile, on_delete=models.CASCADE)
    title = models.CharField(max_length=200) # 제목
    body = models.TextField() # 게시물 설명
    uploadDate = models.DateTimeField(auto_now_add=True) # 처음 업로드 시간
    updateDate = models.DateTimeField(auto_now=True) # 수정 시간
    photo = models.ImageField(blank=True, null=True, upload_to='thumbnail') # 썸네일 # upload_to : static/blog_photo 로 저장해줘
    video = models.FileField(blank=True, null=True, upload_to='video') # 배포시에는 models.FilePathField()사용
    genreName = models.ForeignKey(Genre, null=True, on_delete=models.CASCADE) # 장르
    likes_user = models.ManyToManyField(userProfile, related_name='course_likes', blank=True) # 좋아요 누른 사람
    likes_count = models.PositiveIntegerField(default=0) 
    register_user = models.ManyToManyField(userProfile, related_name='register_user', blank=True)
    register_count = models.PositiveIntegerField(default=0) 
    # 최대 인원 수, 위치, 클래스 날짜 및 시간, 끝나는 시간
    maxRegCount = models.IntegerField(default=0, null=False) 
    startDate = models.DateField(auto_now=False, auto_now_add=False)
    # 강좌 위치
    location = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.title

# 댓글 모델
class Comment(models.Model):
    # comment_id 는 pk로서 존재함
    userId = models.ForeignKey(userProfile, on_delete=models.CASCADE)
    comment = models.TextField('', max_length=100)
    date = models.DateTimeField(auto_now_add=True)
    post = models.ForeignKey(Post, null=True, blank=True, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.comment

Desktop/Dance-prj-main/platformdance/danceapp/views.py
from atexit import register
from django.shortcuts import render, redirect, get_object_or_404
from django.template.defaulttags import comment
from .forms import PostForm, CommentForm, CourseForm, PostModifyForm
from .models import Post, Comment, Genre, Course
from accounts.models import userProfile
from django.core.paginator import Paginator

# 페이지네이션, 객체들 목록을 끊어서 보여주는 것
# from django.core.paginator import Paginator

def index(request):
    # paginator는 삭제 예정
    # 업로드된 영상 게시글
    posts = Post.objects.all().order_by('-uploadDate')
    paginator = Paginator(posts, 8)
    pagenum = request.GET.get('page') # url 부분 ex) @@@?page=1 -> {page:1}
    posts = paginator.get_page(pagenum)
    
    # 업로드된 클래스 게시글
    courses = Course.objects.all().order_by('-uploadDate')
    paginator = Paginator(courses, 8)
    pagenum = request.GET.get('page') # url 부분 ex) @@@?page=1 -> {page:1}
    courses = paginator.get_page(pagenum)

    # likes_ten = Post.objects.all().order_by('-likes_count')[:5] # 모든 포스트 중 택5 -> 쿼리셋
    likes_top_ten = Post.objects.all().order_by('-likes_count') # 모든 포스트 중 택5 -> 딕셔너리 형태
    likes_top_ten_val = Post.objects.all().order_by('-likes_count').values() # 모든 포스트 중 택5 -> 딕셔너리 형태
    likes_top_ten_val = list(likes_top_ten_val)
    # likes_ten = Post.objects.filter(genreName='1').order_by('-likes_count')[:5] # 장르 중 택5

    comment_form = CommentForm()

    context = {
        'posts':posts,
        'courses':courses,
        'comment_form':comment_form,
        'likes_top_ten':likes_top_ten,
        'likes_top_ten_val':likes_top_ten_val,
        # 'rank1':likes_top_ten[0],
        # 'rank2':likes_top_ten[1],
        # 'rank3':likes_top_ten[2],
        # 'rank4':likes_top_ten[3],
        # 'rank5':likes_top_ten[4],
        # 'rank6':likes_top_ten[5],
        # 'rank7':likes_top_ten[6],
        # 'rank8':likes_top_ten[7],
        # 'rank9':likes_top_ten[8],
        # 'rank10':likes_top_ten[9],
    }
    return render(request, 'index.html', context)

# 클래스 만들기
def coursecreate(request):
    print("클래스 만들기 시작")
    # request 메소드가 Post 일 경우 입력값 저장
    if request.method == 'POST' or request.method == 'FILES':
        print("if문 post 요청 받아옴")
        form = CourseForm(request.POST, request.FILES)
        print("form 가져옴")
        print(request.POST)
        # print(form)
        if form.is_valid():
            print("valid 검사 시작")
            unfinished = form.save(commit=False)
            print("commit false 수행")
            print(unfinished)
            unfinished.userId = request.user
            unfinished.save()
            return redirect('index')
    # request method()가 Get일 경우 form 입력 html 띄우기
    else:
        form = CourseForm()
    
    context = {
        'form':form
    }
    return render(request, 'coursecreate.html', context)

# 게시글 작성
def postcreate(request):
    # request 메소드가 Post 일 경우 입력값 저장
    if request.method == 'POST' or request.method == 'FILES':
        form = PostForm(request.POST, request.FILES)
        print(request.POST)
        print(form)
        if form.is_valid():
            unfinished = form.save(commit=False)
            unfinished.userId = request.user
            unfinished.save()
            return redirect('index')
    # request method()가 Get일 경우 form 입력 html 띄우기
    else:
        form = PostForm()
    
    context = {
        'form':form
    }
    return render(request, 'postcreate.html', context)

# 게시글 수정
def modify_post(request, post_id):
    if request.method =='POST' or request.method == 'FILES':
        post = get_object_or_404(Post, pk=post_id)
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            # post = form.save(commit=False)
            # form = PostForm(Post,instance=post)
            # post.title = request.POST['title']
            # post.body = request.POST['body']
            # post.title = form.cleaned_data['title'] # +
            # post.body = form.cleaned_data['body'] # +            
            # post.save()
            form.save()
            return redirect('index')
    # else:
    #     form = PostModifyForm(instance = post)
    return render(request, 'modify_post.html', {'form':form})

# 수정 2 테스트 해보기
# def update(request, article_pk):
#     edit_title = request.POST.get('edit_title')
#     edit_content = request.POST.get('edit_content')
#     article = Article.objects.get(pk=article_pk)
#     article.title = edit_title
#     article.content = edit_content
#     article.save()
#     return redirect('articles:detail', article_pk)

# 게시글 삭제
def delete_post(request, post_id):
    del_post = get_object_or_404(Post, pk=post_id)
    del_post.delete()
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

# def delete_post(request, post_id, user_id):
#     if request.user.is_authenticated:
#         del_post = get_object_or_404(Post, pk=post_id)
#         if request.user == del_post.userId:
#             del_post.delete()
#     return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

# 댓글 저장
def new_comment(request, post_id):
    filled_form = CommentForm(request.POST)
    if filled_form.is_valid():
        finished_form = filled_form.save(commit=False)
        finished_form.userId = request.user
        finished_form.post = get_object_or_404(Post, pk=post_id)
        print("comment:", request.body)
        print("post_id :", post_id)
        finished_form.save()
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

# 댓글 삭제
def delete_comment(request, comment_id):
    del_comment = get_object_or_404(Comment, pk=comment_id)
    del_comment.delete()
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

# 개인 유저 프로필 보기
def user_post_detail(request, userId_id):
    posts = Post.objects.filter(userId=userId_id).order_by('-uploadDate')
    user = get_object_or_404(userProfile, pk=userId_id)
    # username = Post.objects.
    comment_form = CommentForm()
    context = {
        'posts':posts,
        'comment_form':comment_form,
        'user':user,
    }
    return render(request, 'user_post_detail.html', context)

# 게시글 좋아요
def likes(request, post_id):
    if request.user.is_authenticated:    
        post = get_object_or_404(Post, pk=post_id)
        # check_like_post = 
        if request.user in post.likes_user.all():
        # if post.likes_user.filter(pk=request.user.pk).exists():
            post.likes_user.remove(request.user)
            post.likes_count -= 1
            post.save()    
        else:
            post.likes_user.add(request.user)
            post.likes_count += 1
            post.save()
    # 현재 내가 있는 페이지로 redirect 
    return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))     

# 게시글 세부 페이지로 이동
def post_datail(request, post_id):
    post = Post.objects.get(id = post_id)
    post.hits += 1
    post.save()
    comment_form = CommentForm()
    context = {
        'post':post,
        'comment_form':comment_form,
    }
    return render(request, 'post_detail.html', context)

# 장르 페이지
def genre_post(request):
    genre_id = request.GET.get('genre_id', None)
    genre = Genre.objects.get(id=int(genre_id))
    posts = Post.objects.filter().order_by('-uploadDate')
    likes_top = Post.objects.filter(genreName=int(genre_id)).order_by('-likes_count')
    comment_form = CommentForm()
    context = {
        'genre':genre,
        'posts':posts,
        'comment_form':comment_form,
        'likes_top':likes_top,
        # 장르별 게시글이 10개가 안 넘어서 오류 뜸
        # 'rank1':likes_top[0],
        # 'rank2':likes_top[1],
        # 'rank3':likes_top[2],
        # 'rank4':likes_top[3],
        # 'rank5':likes_top[4],
        # 'rank6':likes_top[5],
        # 'rank7':likes_top[6],
        # 'rank8':likes_top[7],
        # 'rank9':likes_top[8],
        # 'rank10':likes_top[9],
    }
    return render(request, 'genre_post.html', context)

# 장르에 맞는 클레스 출력
def genre_course(request):
    genre_id = request.GET.get('genre_id', None)
    genre = Genre.objects.get(id=int(genre_id))
    courses = Course.objects.filter(genreName=genre).order_by('-uploadDate')
    likes_top_ten = Course.objects.all().order_by('-likes_count') # 모든 포스트 중 택5 -> 딕셔너리 형태
    comment_form = CommentForm()
    context = {
        'genre':genre,
        'courses':courses,
        'comment_form':comment_form,
        'likes_top_ten':likes_top_ten,
    }
    return render(request, 'genre_course.html', context)

# 클래스 좋아요
def course_likes(request, course_id):
   if request.user.is_authenticated:    
       course = get_object_or_404(Course, pk=course_id)
       if request.user in course.likes_user.all():
       # if post.likes_user.filter(pk=request.user.pk).exists():
           course.likes_user.remove(request.user)
           course.likes_count -= 1
           course.save()    
       else:
           course.likes_user.add(request.user)
           course.likes_count += 1
           course.save()
   # 현재 내가 있는 페이지로 redirect 
   return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

# 클래스 상세보기
def course_detail(request, course_id):
    course = get_object_or_404(Course, pk=course_id)
    context = {
        'course': course,
    }
    return render(request, 'course_detail.html', context)

# 클래스 신청하기
def regCourse(request, course_id):
   if request.user.is_authenticated:    
       course = get_object_or_404(Course, pk=course_id)
       if request.user in course.register_user.all():
    #    if course.register_user.filter(pk=request.user.pk).exists():
           course.register_user.remove(request.user)
           course.register_count -= 1
           course.save()    
       else:
           course.register_user.add(request.user)
           course.register_count += 1
           course.save()
   # 현재 내가 있는 페이지로 redirect 
   return redirect(request.META.get('HTTP_REFERER', 'redirect_if_referer_not_found'))

# 마이페이지 정보 전달
def mypage(request, user_id):

Desktop/Dance-prj-main/platformdance/danceapp/templates/about_us.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<section id = "aboutUs-section">
    <p id="aboutUs-title">Who We Are</p>
    <div>
        <p style="font-size:30px;">We live to discover</p>
        <p style="font-size:50px;color:#FF5656">Untold Originals.</p>
        <div id="aboutUs-contents">
            <p style="font-weight:800;margin-bottom:33px;line-height:30px;">진정한 독창성이란 무엇일까?</p>
            <div class="aboutUs-detail-content">
                CHOO:OOM은 그 답을 찾기 위해 1995년부터 끝없는 여정을 시작했습니다. 놓쳐서는 안될 드라마, 시상식을 휩쓰는 영화, 매일 챙겨 보고 싶은 리얼리티 프로그램등을 제작하며 독창적인 영역을 개척해온 CHOO:OOM은 차세대 K-팝스타를 발굴하고 새로운 돌풍을 일으킬 애니메이션과 미국의 브로드웨이와 영국의 웨스트엔드, 다른 아시아 지역을 포함한 세계 무대에 선보일 수 있는 수준 높은 뮤지컬을 제작하여 그 무대를 점점 더 넓히고 있습니다. 진정한 독창성은 나이와 세대, 언어의 장벽마저 뛰어넘습니다. 새로운 캐릭터와 스토리에 모두가 공감할 때 우리는 하나가 됩니다.
            </div>
            <div class="updown-line"></div>
            <div class="aboutUs-detail-content">
                낯선 것에서 찾아낸 공감대를 사랑하고 그 과정에서 기쁨을 느끼는 CHOO:OOM은 우리만의 독창적인 것, Untold Originals를 찾아 오늘도 끝없는 여정을 이어갑니다.
            </div>
        </div>
    </div>
</section>
{% endblock %}

Desktop/Dance-prj-main/platformdance/danceapp/templates/course_detail백엔드.html
<h1>클래스 세부 정보</h1>

<h2>genreName: {{ course.genreName.name }}</h2>

<div>
    <h2>클래스 소개</h2>
    <img style="width: 30%;" src="{{ course.photo.url }}" alt=""><br>
    <a> title: {{ course.title }}</a><br>
    <a> body: {{ course.body }}</a><br>
</div>

<div>
    <h2>댄서 소개</h2>
    <img style="width: 30%;" src="{{ course.userId.profilephoto }}" alt=""><br>
    <a>댄서 이름: {{ course.userId.nickname}}</a><br>
    <a>댄스 스킬: {{ course.userId.danceSkill}}</a><br>
    <a>댄서 전화번호: {{ course.userId.phoneNum}}</a>
</div>

<div>
    <h2>장소</h2>
    <a>위치: {{ course.location }}</a>
</div>

<form action="{% url 'regCourse' course.id%}" method="POST">
    {% csrf_token %}
    <input type="submit" value="신청하기">
</form>

Desktop/Dance-prj-main/platformdance/danceapp/templates/coursecreate.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CourseCreate</title>

    <style>
        @import url('https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=Gothic+A1:wght@900&display=swap');

        html {
            background-color: black;
        }

        body {
            margin: 0;
            padding: 0;
            background-image: url('../../static/img/background1.png');
            background-color: rgba(0, 0, 0, 0.6);
            background-blend-mode: multiply;
            background-size: 100vw;
            background-repeat: no-repeat;
            background-position: center bottom;
            display: flex;
        }

        p,
        div {
            color: white;
            margin: 0;
            font-family: 'Gothic A1', serif;
        }

        a {
            text-decoration-line: none;
        }

        #secLeft {
            width: 140px;
            height: 100vh;
            display: flex;
            flex-direction: column;
        }

        #back {
            width: 40px;
            height: 40px;
            margin-left: 100px;
            margin-top: 120px;
        }

        #secCenter {
            display: flex;
            flex-grow: 1;
            flex-wrap: nowrap;
            justify-content: center;
        }

        #divLogo {
            width: 100%;
            height: 96px;
            margin-top: 89px;
            margin-bottom: 67px;
            text-align: center;
        }

        #logo {
            color: white;
            font-family: 'DM Serif Display', serif;
            font-size: 70px;
        }

        .uploadInfo {
            font-size: 22px;
        }

        .uploadInfo .form-control {
            width: 511px;
            height: 70px;
            background-color: rgba(255, 255, 255, 0.6);
            border: 0px solid #ffffff;
            border-radius: 15px;
            color: black;
            font-size: 20px;
            font-family: 'Gothic A1', sans-serif;
            margin-top: 17px;
            padding-left: 34px;
            padding-right: 34px;
        }

        .uploadInfo .form-control::placeholder {
            color: black;
        }

        #content {
            height: 210px;
            padding-top: 20px;
            padding-bottom: 20px;
        }

        select::-ms-expand {
            display: none;
        }

        #id_genreName {
            width: 579px;
            height: 70px;
        }

        .uploadInfo select {
            background: url("../../static/img/black_arrow_down.png") no-repeat 95% 50%;
            background-size: 35px;
            text-align: center;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
        }

        .uploadInfo select option {
            background: rgba(0, 0, 0);
            color: #ffffff;
        }

        #id_photo {
            width: 0px;
            height: 0px;
            visibility: visible;
        }

        .uploadInfo label {
            display: inline-flex;
            flex-direction: column;
            text-align: center;
            justify-content: center;
        }

        .uploadInfo button {
            width: 580px;
        }

        #fileSelected {
            margin-top: 10px;
        }

        #fileName {
            font-size: 16px;
            font-family: 'Gothic A1', sans-serif;
        }

        #upload {
            width: 579px;
            height: 87px;
            background-color: #FF5656;
            border-radius: 30px;
            color: white;
            font-family: 'Gothic A1', sans-serif;
            font-size: 30px;
            margin-top: 130px;
            margin-bottom: 89px;
        }
    </style>
</head>

<body>
    <section id="secLeft">
        <a href="javascript:window.history.back();"><img id="back" src="{% static 'img/white_back.png' %}" alt="뒤로"></a>
    </section>

    <section id="secCenter">
        <div id="wrapper">
            <div id="divLogo">
                <a href="{% url 'index' %}">
                    <p id="logo">CHOO:OOM</p>
                </a>
            </div>
            <!--클래스 업로드 폼-->
            <form action="{% url 'coursecreate' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <!--제목-->
                <div class="uploadInfo" style="margin-bottom:58px;">
                    <p>Title</p>
                    {{ form.title }}
                </div>
                <!--설명-->
                <div class="uploadInfo" style="margin-bottom:25px;">
                    <p>Introduction</p>
                    {{ form.body }}
                </div>
                <!--장르 선택-->
                <div class="uploadInfo" style="margin-bottom:53px;">
                    <p>What's your Genre?</p>
                    {{ form.genreName }}
                </div>
                <!--장소 선택-->
                <div class="uploadInfo" style="margin-bottom:67px;">
                    <p>Place</p>
                    {{ form.location }}
                </div>
                <!--날짜 시간 선택-->
                <div class="uploadInfo" style="margin-bottom:58px;">
                    <p>Date/Time</p>
                    {{ form.startDate }}
                </div>
                <!--메인 이미지 선택-->
                <div class="uploadInfo" style="height: 152px;">
                    <p>Main Image</p>
                    <label class="form-control" for="id_photo">파일 선택</label>
                    <div id="fileSelected">
                        <img id="fileImage" src="">
                        <p id="fileName"></p>
                    </div>
                    {{ form.photo }}
                </div>
                <!--업로드 버튼-->
                <input type="submit" id="upload" type="submit">
                <!-- <input id="upload" type="submit" value="Upload"></input> -->
            </form>
        </div>
    </section>
</body>

<script>
    // 파일 선택
    function loadFile(input) {
        var container = document.getElementById('fileSelected');
        var file = input.files[0];

        var newImage = document.getElementById("fileImage");
        newImage.src = URL.createObjectURL(file);
        newImage.style.maxWidth = "100px";
        newImage.style.maxHeight = "100px";
        newImage.style.visibility = "visible";

        var name = document.getElementById('fileName');
        name.textContent = file.name;
    }
</script>

</html>

Desktop/Dance-prj-main/platformdance/danceapp/templates/coursecreate백엔드.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/test.css' %}">
</head>

<body>
    <div class="mainbox">
        <div class="table-row">
            <div class="title-box">
                <header>
                    <a href="{% url 'index' %}">CHOO:OOM</a>
                </header>
            </div>
            <main class="rounded" style="background-color : white;">
                <section class="section-box">
                    <h1 style="color: black;">클래스 등록</h1>
                    <hr class="mt-4">
                    <div class="container" style="margin-top: 10px; background-color: white;">
                        <form action="{% url 'coursecreate' %}" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="title" style="color: black; font-size:large;">제목</label>
                                {{ form.title }}
                            </div>
                            <div class="form-group">
                                <label for="content" style="color: black; font-size: large;">내용</label>
                                {{ form.body }}
                            </div>
                            <div class="container" style="padding-top:50px;">
                                <hr class="mt-4">
                                <div class="row">
                                    <div class="col-6 col-sm-3">
                                        <label for="id_photo" style="color: black; font-size: large;">사진</label>
                                    </div>
                                    <div class="col-6 col-sm-3">
                                        {{ form.photo }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 col-sm-3">
                                        <label for="id_video" style="color: black; font-size: large;">비디오</label>
                                    </div>
                                    <div class="col-6 col-sm-3">
                                        {{ form.video }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 col-sm-3">
                                        <label for="id_genreName" style="color: black; font-size: large;">장르</label>
                                    </div>
                                    <div class="col-6 col-sm-3">
                                        {{ form.genreName }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 col-sm-3">
                                        <label for="id_startDate" style="color: black; font-size: large;">강의 시작일</label>
                                    </div>
                                    <div class="col-6 col-sm-3">
                                        {{ form.startDate }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 col-sm-3">
                                        <label for="id_location" style="color: black; font-size: large;">위치</label>
                                    </div>
                                    <div class="col-6 col-sm-3">
                                        {{ form.location }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 col-sm-3">
                                        <label for="id_maxRegCount" style="color: black; font-size: large;">최대 수강 인원</label>
                                    </div>
                                    <div class="col-6 col-sm-3">
                                        {{ form.maxRegCount }}
                                    </div>
                                </div>
                                <hr class="mt-4">
                                <div class="d-grid gap-2 col-6 mx-auto" style="padding-top: 10px; text-align: center;">
                                    <input type="submit" class="btn btn-primary btn-lg" value="등록하기">
                                </div>
                            </div>
                        </form>

                    </div>
            </main>
        </div>
        </section>

    </div>

</body>

</html>